# Generated by Django 5.2 on 2026-09-26 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data e hora"
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FALHA", "Tentativa de login com falha"),
                            ("ACESSO", "Acesso a página"),
                            ("ACESSO_NEGADO", "Acesso negado"),
                            ("CRIACAO", "Criação"),
                            ("ALTERACAO", "Alteração"),
                            ("EXCLUSAO", "Exclusão"),
                            ("EXPURGO", "Expurgo por retenção"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "usuario_login",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Login do usuário"
                    ),
                ),
                (
                    "entidade",
                    models.CharField(
                        blank=True,
                        help_text="Modelo afetado, no formato app.Modelo.",
                        max_length=100,
                        verbose_name="Entidade",
                    ),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID do objeto"
                    ),
                ),
                (
                    "objeto_repr",
                    models.CharField(blank=True, max_length=200, verbose_name="Objeto"),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descrição"
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        blank=True,
                        help_text="Valores do objeto ou campos alterados (antes/depois).",
                        null=True,
                        verbose_name="Dados",
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Navegador"
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Método HTTP"
                    ),
                ),
                (
                    "caminho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Caminho"
                    ),
                ),
                (
                    "status_http",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Status HTTP"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoria",
                "verbose_name_plural": "Registros de auditoria",
                "ordering": ["-data_hora", "-id"],
                "indexes": [
                    models.Index(fields=["-data_hora"], name="idx_audit_data"),
                    models.Index(
                        fields=["usuario", "-data_hora"], name="idx_audit_usuario_data"
                    ),
                    models.Index(
                        fields=["acao", "-data_hora"], name="idx_audit_acao_data"
                    ),
                    models.Index(
                        fields=["entidade", "objeto_id"], name="idx_audit_entidade_obj"
                    ),
                ],
            },
        ),
    ]
