# Generated by Django 5.2 on 2026-09-12 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('tipo', models.SmallIntegerField(choices=[(1, 'Teórica'), (2, 'Prática (código)')], default=1, verbose_name='Tipo')),
                ('ordem', models.SmallIntegerField(default=1, verbose_name='Ordem de exibição')),
                ('prazo', models.DateTimeField(blank=True, help_text='Opcional. Deixe em branco para atividade sem prazo.', null=True, verbose_name='Prazo de entrega')),
                ('publicada', models.BooleanField(default=True, verbose_name='Visível aos discentes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativa'), (2, 'Trancada'), (3, 'Cancelada')], db_index=True, default=1, verbose_name='Situação')),
                ('data_matricula', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da matrícula')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['turma', 'discente__first_name'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da trilha')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.SmallIntegerField(default=1, help_text='Menor número aparece primeiro.', verbose_name='Ordem de exibição')),
                ('publicada', models.BooleanField(default=True, help_text='Desmarque para preparar a trilha sem exibi-la aos alunos.', verbose_name='Visível aos discentes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Trilha de aprendizagem',
                'verbose_name_plural': 'Trilhas de aprendizagem',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('periodo', models.CharField(help_text='Ex.: 2026/1', max_length=20, verbose_name='Período')),
                ('ativa', models.BooleanField(db_index=True, default=True, verbose_name='Turma ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['-periodo', 'nome'],
            },
        ),
    ]
