# Generated by Django 5.2 on 2026-09-13 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0004_matricula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhaAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da trilha')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ordem', models.SmallIntegerField(default=1, help_text='Menor número aparece primeiro.', verbose_name='Ordem de exibição')),
                ('publicada', models.BooleanField(default=True, help_text='Desmarque para preparar a trilha sem exibi-la aos alunos.', verbose_name='Visível aos discentes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='turmas.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Trilha de aprendizagem',
                'verbose_name_plural': 'Trilhas de aprendizagem',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('enunciado', models.TextField(verbose_name='Enunciado')),
                ('tipo', models.CharField(choices=[('TEORICA', 'Teórica'), ('PRATICA', 'Prática (código)')], default='TEORICA', max_length=10, verbose_name='Tipo')),
                ('ordem', models.SmallIntegerField(default=1, verbose_name='Ordem de exibição')),
                ('prazo', models.DateTimeField(blank=True, help_text='Opcional. Deixe em branco para atividade sem prazo.', null=True, verbose_name='Prazo de entrega')),
                ('publicada', models.BooleanField(default=True, verbose_name='Visível aos discentes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.trilhaaprendizagem', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConclusaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True, verbose_name='Concluída em')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='core.atividade', verbose_name='Atividade')),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Discente')),
            ],
            options={
                'verbose_name': 'Conclusão de atividade',
                'verbose_name_plural': 'Conclusões de atividades',
                'ordering': ['-data_conclusao'],
                'indexes': [models.Index(fields=['discente', 'atividade'], name='idx_conclusao_disc_ativ')],
                'constraints': [models.UniqueConstraint(fields=('atividade', 'discente'), name='uq_conclusao_atividade_discente')],
            },
        ),
        migrations.AddIndex(
            model_name='trilhaaprendizagem',
            index=models.Index(fields=['turma', 'ordem'], name='idx_trilha_turma_ordem'),
        ),
        migrations.AddConstraint(
            model_name='trilhaaprendizagem',
            constraint=models.UniqueConstraint(fields=('turma', 'titulo'), name='uq_trilha_turma_titulo'),
        ),
        migrations.AddConstraint(
            model_name='trilhaaprendizagem',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gte', 0)), name='ck_trilha_ordem_nao_negativa'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['trilha', 'ordem'], name='idx_atividade_trilha_ordem'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('trilha', 'titulo'), name='uq_atividade_trilha_titulo'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gte', 0)), name='ck_atividade_ordem_nao_negativa'),
        ),
    ]
