# Generated by Django 5.2 on 2026-09-12 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='discente',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'perfil': 'DISCENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL, verbose_name='Discente'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.trilhaaprendizagem', verbose_name='Trilha'),
        ),
        migrations.AddField(
            model_name='turma',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'is_active': True, 'perfil': 'DOCENTE'}, on_delete=django.db.models.deletion.PROTECT, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL, verbose_name='Docente responsável'),
        ),
        migrations.AddField(
            model_name='trilhaaprendizagem',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='core.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='core.turma', verbose_name='Turma'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['trilha', 'ordem'], name='idx_atividade_trilha_ordem'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('trilha', 'titulo'), name='uq_atividade_trilha_titulo'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gte', 0)), name='ck_atividade_ordem_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('docente', 'nome', 'periodo'), name='uq_turma_docente_nome_periodo'),
        ),
        migrations.AddIndex(
            model_name='trilhaaprendizagem',
            index=models.Index(fields=['turma', 'ordem'], name='idx_trilha_turma_ordem'),
        ),
        migrations.AddConstraint(
            model_name='trilhaaprendizagem',
            constraint=models.UniqueConstraint(fields=('turma', 'titulo'), name='uq_trilha_turma_titulo'),
        ),
        migrations.AddConstraint(
            model_name='trilhaaprendizagem',
            constraint=models.CheckConstraint(condition=models.Q(('ordem__gte', 0)), name='ck_trilha_ordem_nao_negativa'),
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=['discente', 'status'], name='idx_matricula_discente_status'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('turma', 'discente'), name='uq_matricula_turma_discente'),
        ),
    ]
