# Generated by Django 5.2 on 2026-09-14 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('TEORICA', 'Teórica'), ('PRATICA', 'Prática (código)')], default='TEORICA', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ConclusaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True, verbose_name='Concluída em')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusoes', to='core.atividade', verbose_name='Atividade')),
                ('discente', models.ForeignKey(limit_choices_to={'is_active': True, 'perfil': 'DISCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='atividades_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Discente')),
            ],
            options={
                'verbose_name': 'Conclusão de atividade',
                'verbose_name_plural': 'Conclusões de atividades',
                'ordering': ['-data_conclusao'],
                'indexes': [models.Index(fields=['discente', 'atividade'], name='idx_conclusao_disc_ativ')],
                'constraints': [models.UniqueConstraint(fields=('atividade', 'discente'), name='uq_conclusao_atividade_discente')],
            },
        ),
    ]
