# Generated by Django 5.2 on 2026-09-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0004_alter_chamada_turma'),
        ('core', '0003_alter_atividade_tipo_conclusaoatividade'),
        ('turmas', '0004_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trilhaaprendizagem',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trilhas', to='turmas.turma', verbose_name='Turma'),
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
