# Generated by Django 5.2 on 2026-09-12 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_chamada', models.CharField(max_length=6, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='core.turma', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'chamada',
                'verbose_name_plural': 'chamadas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Registro_de_Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registro em')),
                ('chamada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='chamada.chamada')),
                ('discente', models.ForeignKey(limit_choices_to={'is_active': True, 'perfil': 'DISCENTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Registro de Presenca',
            },
        ),
    ]
