# Generated by Django 5.2 on 2026-09-12 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_de_presenca',
            options={'verbose_name': 'Registro de Presenca', 'verbose_name_plural': 'registros de Presenca'},
        ),
        migrations.AddConstraint(
            model_name='registro_de_presenca',
            constraint=models.UniqueConstraint(fields=('chamada', 'discente'), name='uq_presenca_unica_por_aluno'),
        ),
    ]
