# Generated by Django 5.2 on 2026-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0002_alter_registro_de_presenca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamada',
            name='limite_uso',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantidade máxima de alunos que podem confirmar presença com este token.', verbose_name='Limite de uso do token'),
        ),
    ]
