# Generated by Django 5.2 on 2026-09-14 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamada', '0003_chamada_limite_uso'),
        ('turmas', '0004_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamada',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas', to='turmas.turma', verbose_name='Turma'),
        ),
    ]
