# Generated by Django 5.2 on 2026-09-22 02:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_turma_docente_alter_trilhaaprendizagem_turma_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.TextField(verbose_name='Resposta')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('aluno', models.ForeignKey(limit_choices_to={'perfil': 'DISCENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='core.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota')),
                ('feedback_professor', models.TextField(blank=True, verbose_name='Feedback do professor')),
                ('avaliado_em', models.DateTimeField(auto_now=True, verbose_name='Avaliado em')),
                ('submissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_oficial', to='entregas.submissao', verbose_name='Submissão')),
            ],
            options={
                'verbose_name': 'Avaliação oficial',
                'verbose_name_plural': 'Avaliações oficiais',
            },
        ),
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parecer_texto', models.TextField(blank=True, verbose_name='Parecer')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro de API')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('submissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_ia', to='entregas.submissao', verbose_name='Submissão')),
            ],
            options={
                'verbose_name': 'Análise de IA',
                'verbose_name_plural': 'Análises de IA',
            },
        ),
        migrations.AddConstraint(
            model_name='submissao',
            constraint=models.UniqueConstraint(fields=('atividade', 'aluno'), name='uq_submissao_atividade_aluno'),
        ),
    ]
