# Generated by Django 5.2 on 2026-09-26 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceiteTermos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=10, verbose_name='Versão aceita')),
                ('aceito_em', models.DateTimeField(auto_now_add=True, verbose_name='Aceito em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aceito_em'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'versao'), name='uq_aceite_usuario_versao')],
            },
        ),
    ]
