# Generated by Django 5.2 on 2026-09-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='semestre',
            new_name='periodo',
        ),
    ]
