# Generated by Django 5.2 on 2026-09-04 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_rename_semestre_turma_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='turma',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 4, 12, 58, 35, 995149, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
