# Generated by Django 5.2 on 2026-09-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_turma_ativa_turma_data_criacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('INATIVA', 'Inativa')], default='ATIVA', max_length=10)),
                ('data_matricula', models.DateTimeField(auto_now_add=True)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.turma')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('turma', 'discente'), name='matricula_unica_por_turma')],
            },
        ),
    ]
